### ISSUE TITLE
Downside?

### ISSUE THREAD

**Issue by tillkruss** [ethanhann/Laravel-RedisStore#1]
Is there any downside to compressing data? If not we, should merge this into the framework.

**Comment by ethanhann** [comment]
I wrote a PR for Laravel with this functionality before making this repo. I explained why it is useful (laravel/internals/issues/370), but it was rejected by the project lead (laravel/framework/pull/17340).

There is additional CPU load on the server where Laravel is running. The amount of CPU load depends on the size of your cached data and access rate. If you are caching small items under 1MB (where 1MB=uncompressed size) with a high access rate of 1k requests/second, you will barely see a difference in load. Another small downside is that you cannot easily examine the items in the cache with an external tool like Medis or redis-cli because they will not be human readable.

**Comment by tillkruss** [comment]
Cool, thanks!
